import formsPlugin from '@tailwindcss/forms';
import containerQueriesPlugin from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface-variant": "#353534",
              "on-secondary-container": "#c8b37d",
              "error": "#ffb4ab",
              "background": "#131313",
              "on-error": "#690005",
              "on-tertiary-container": "#254188",
              "on-surface": "#e5e2e1",
              "surface-tint": "#e9c349",
              "surface-container-lowest": "#0e0e0e",
              "inverse-primary": "#735c00",
              "on-tertiary-fixed": "#00174b",
              "on-secondary-fixed-variant": "#544519",
              "tertiary-fixed-dim": "#b4c5ff",
              "secondary-fixed": "#f7e1a6",
              "outline": "#99907c",
              "primary-container": "#d4af37",
              "on-secondary": "#3c2f05",
              "outline-variant": "#4d4635",
              "on-primary-fixed": "#241a00",
              "inverse-surface": "#e5e2e1",
              "on-primary-fixed-variant": "#574500",
              "tertiary": "#bfcdff",
              "on-background": "#e5e2e1",
              "on-primary-container": "#554300",
              "on-secondary-fixed": "#241a00",
              "secondary": "#dac58d",
              "surface-container": "#201f1f",
              "surface-container-low": "#1c1b1b",
              "primary-fixed-dim": "#e9c349",
              "tertiary-fixed": "#dbe1ff",
              "surface-bright": "#393939",
              "error-container": "#93000a",
              "secondary-container": "#544519",
              "on-primary": "#3c2f00",
              "surface-container-highest": "#353534",
              "inverse-on-surface": "#313030",
              "primary": "#f2ca50",
              "on-surface-variant": "#d0c5af",
              "surface-dim": "#131313",
              "on-error-container": "#ffdad6",
              "secondary-fixed-dim": "#dac58d",
              "on-tertiary-fixed-variant": "#27438a",
              "surface-container-high": "#2a2a2a",
              "surface": "#131313",
              "on-tertiary": "#082b72",
              "tertiary-container": "#97b0ff",
              "primary-fixed": "#ffe088"
          },
          fontFamily: {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
          },
          borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      },
  },
  plugins: [formsPlugin, containerQueriesPlugin],
}
